@echo off
REM Generated by scripts/autostart.py. Safe to read, edit or delete.
REM Delete the shortcut in shell:startup to stop Tessa starting at login,
REM or turn it off in Task Manager > Startup.
cd /d "C:\dev\tessa"
set "LOGDIR=C:\dev\tessa\data\logs"

REM -- WAIT FOR THE AUDIO STACK ------------------------------------------
REM A Startup-folder shortcut fires as soon as the shell is up, which can be
REM BEFORE the audio endpoints have finished enumerating. With --voice that
REM means opening a microphone that is not there yet: she either comes up deaf
REM or dies, in a minimised window nobody is watching. A Scheduled Task has a
REM built-in delay and a Startup shortcut does not, so the wait lives here.
REM Change the number or delete these two lines if it is not wanted.
timeout /t 20 /nobreak > nul
if not exist "%LOGDIR%" mkdir "%LOGDIR%"
for /f "tokens=1-3 delims=/-. " %%a in ("%DATE%") do set "STAMP=%%c-%%b-%%a"
echo. >> "%LOGDIR%\daemon-%STAMP%.log"
echo ==== started %DATE% %TIME% ==== >> "%LOGDIR%\daemon-%STAMP%.log"
REM -- THE DOUBLE-START GUARD --------------------------------------------
REM Exit 3 means a daemon is already live, so this login must not start a
REM second one. Two overlapping daemons forked the audit chain once already.
"C:\Users\SERIOUS-PC\AppData\Local\Programs\Python\Python312\python.exe" scripts\autostart.py --check >> "%LOGDIR%\daemon-%STAMP%.log" 2>&1
if errorlevel 3 goto :alreadyrunning

"C:\Users\SERIOUS-PC\AppData\Local\Programs\Python\Python312\python.exe" core\server.py --dev --voice --stt-model base >> "%LOGDIR%\daemon-%STAMP%.log" 2>&1
echo ==== exited with %ERRORLEVEL% at %TIME% ==== >> "%LOGDIR%\daemon-%STAMP%.log"
REM A non-zero exit leaves this window open so a failed start is VISIBLE.
if not "%ERRORLEVEL%"=="0" (
  echo.
  echo Tessa exited with %ERRORLEVEL%. The log is at:
  echo   %LOGDIR%\daemon-%STAMP%.log
  pause
)
exit /b 0

:alreadyrunning
REM Not an error, and deliberately quiet: a daemon is already up and doing its
REM job. Recorded in the log so "why did nothing start at login" is answerable.
echo ==== skipped: a daemon was already running ==== >> "%LOGDIR%\daemon-%STAMP%.log"
exit /b 0
